"""Testo pixel mascot animations.

Every animation is a list of frames; a frame is a list of equal-length
strings where each character indexes PALETTE and "." is transparent.
The same grids drive the React mascot components (see
frontend/src/components/mascot/animations.ts, generated by export_ts.py)
and the terminal player (testo_core.mascot.render).

Play in a terminal:  python -m testo_core.mascot flex
"""

from __future__ import annotations

Frame = list[str]
Animation = list[Frame]

# Char -> hex color. Shared by web and CLI renderers.
PALETTE: dict[str, str] = {
    "o": "#232733",  # outline
    "s": "#f2b380",  # skin
    "d": "#cd8756",  # skin shade
    "h": "#ffd9ae",  # skin highlight
    "w": "#3b82f6",  # wristband (brand blue)
    "W": "#1d4ed8",  # wristband shade
    "r": "#ef4444",  # red glove
    "R": "#a61b1b",  # red glove shade
    "u": "#3b82f6",  # blue glove
    "U": "#1e40af",  # blue glove shade
    "b": "#c46a1f",  # brick
    "B": "#8a4210",  # brick shade
    "y": "#ffd23e",  # impact spark
    "x": "#ffffff",  # flash / glove shine
    "t": "#7dd3fc",  # sweat drop
    "p": "#e9e9ef",  # bandage
    "g": "#8b93a3",  # debris / speed lines
}


def _blank(width: int, height: int) -> Frame:
    return ["." * width for _ in range(height)]


def _paste(canvas: Frame, sprite: Frame, x: int, y: int) -> Frame:
    """Overlay sprite onto canvas at (x, y); '.' pixels stay transparent."""
    out = list(canvas)
    for sy, srow in enumerate(sprite):
        cy = y + sy
        if not 0 <= cy < len(out):
            continue
        row = list(out[cy])
        for sx, ch in enumerate(srow):
            cx = x + sx
            if ch != "." and 0 <= cx < len(row):
                row[cx] = ch
        out[cy] = "".join(row)
    return out


def _mirror(sprite: Frame, swap: dict[str, str]) -> Frame:
    table = str.maketrans(swap)
    return [row[::-1].translate(table) for row in sprite]


# ---------------------------------------------------------------- flex ----
# Classic flexed-arm icon: knuckled fist top-right, blue wristband, thick
# diagonal forearm, bicep ball that pumps from relaxed to peak. 20 x 18.

_FLEX_RELAXED: Frame = [
    "..........oooooooooo",
    "..........osssssssso",
    "..........oshdsdsdso",
    "..........ossdsdsdso",
    "..........ossdsdsdso",
    ".........oosddddddso",
    "........ooWwwwWooooo",
    ".......ooWwwwWoo....",
    "......oodssssso.....",
    ".....oodsssssoo.....",
    "....oodsssssoo......",
    "....odsssssoo.......",
    "..ooosssssssooo.....",
    ".oosssssssssssoo....",
    ".ossssssssssssso....",
    ".ossssssssssddso....",
    ".ooossssssssdooo....",
    "...ooooooooooo......",
]

_FLEX_MID: Frame = [
    "..........oooooooooo",
    "..........osssssssso",
    "..........oshdsdsdso",
    "..........ossdsdsdso",
    "..........ossdsdsdso",
    ".........oosddddddso",
    "........ooWwwwWooooo",
    ".......ooWwwwWoo....",
    "......oodssssso.....",
    ".....oodsssssoo.....",
    "...ooodsssssoo......",
    ".ooosdssssssooo.....",
    "oossssssssssssoo....",
    "osshhsssssssssso....",
    "oshhssssssssssso....",
    "osssssssssssddso....",
    "ooosssssssssdooo....",
    "..oooooooooooo......",
]

_FLEX_PEAK: Frame = [
    "..........oooooooooo",
    "..........osssssssso",
    "..........oshdsdsdso",
    "..........ossdsdsdso",
    "..........ossdsdsdso",
    ".........oosddddddso",
    "........ooWwwwWooooo",
    ".......ooWwwwWoo....",
    "...ooooodssssso.....",
    ".ooosssdsssssoo.....",
    "oossssdsssssssoo....",
    "osshhdssssssssso....",
    "oshhssssssssssso....",
    "osssssssssssssso....",
    "osssssssssssssso....",
    "osssssssssssddso....",
    "ooosssssssssdooo....",
    "..oooooooooooo......",
]

_FLEX_PEAK_SHINE: Frame = _paste(
    _FLEX_PEAK,
    [
        "x.x",
        ".x.",
        "x.x",
    ],
    1,
    4,
)

FLEX: Animation = [_FLEX_RELAXED, _FLEX_MID, _FLEX_PEAK, _FLEX_PEAK_SHINE, _FLEX_PEAK, _FLEX_MID]

# --------------------------------------------------------------- smash ----
# Hammer fist drops through a stack of bricks, karate-style. 22 x 18.

_BRICKS_INTACT: Frame = [
    "..obbbbbbbbobbbbbbbo..",
    "..oBBBBBBBBoBBBBBBBo..",
    "..obbbbbbbbobbbbbbbo..",
    "..oBBBBBBBBoBBBBBBBo..",
    "..obbbbbbbbobbbbbbbo..",
    "..oBBBBBBBBoBBBBBBBo..",
]

_SMASH_HAND: Frame = [
    "oosssoo",
    "ossssso",
    "ossssso",
    "odddddo",
    ".ooooo.",
]


def _smash_arm(canvas: Frame, hand_y: int) -> Frame:
    """Arm reaching in from the top edge with the hand at hand_y."""
    for y in range(hand_y):
        canvas = _paste(canvas, ["oWwWo"], 8, y)
    return _paste(canvas, _SMASH_HAND, 7, hand_y)


_SMASH_RAISED: Frame = _smash_arm(_paste(_blank(22, 18), _BRICKS_INTACT, 0, 12), 2)

_SMASH_DROP: Frame = _smash_arm(
    _paste(
        _paste(
            _blank(22, 18),
            [
                "g............g",
                "g............g",
            ],
            4,
            4,
        ),
        _BRICKS_INTACT,
        0,
        12,
    ),
    5,
)

_SMASH_CONTACT: Frame = _smash_arm(
    _paste(
        _paste(
            _blank(22, 18),
            [
                "..obbbbbbboobbbbbbbo..",
                "..oBBBBBBBooBBBBBBBo..",
                "..obbbbbbbbobbbbbbbo..",
                "..oBBBBBBBBoBBBBBBBo..",
                "..obbbbbbbbobbbbbbbo..",
                "..oBBBBBBBBoBBBBBBBo..",
            ],
            0,
            12,
        ),
        [
            ".y.........y.",
            "yx.........xy",
            "x...........x",
        ],
        4,
        10,
    ),
    7,
)

_SMASH_BREAK: Frame = _smash_arm(
    _paste(
        _blank(22, 18),
        [
            "...yx..........xy.....",
            "..g..............g....",
            ".g..bB........Bb....g.",
            "..obbbbbbb..bbbbbbbo..",
            "..oBBBBBBo..oBBBBBBo..",
            ".obbbbbbbo..obbbbbbbo.",
            ".oBBBBBBBo..oBBBBBBBo.",
            "obbbbbbbbo..obbbbbbbbo",
            "oBBBBBBBBo..oBBBBBBBBo",
        ],
        0,
        9,
    ),
    9,
)

_SMASH_THROUGH: Frame = _smash_arm(
    _paste(
        _blank(22, 18),
        [
            ".g................g...",
            ".gbB....y....y...Bbg..",
            "obbbbbbo......obbbbbbo",
            "oBBBBBBo......oBBBBBBo",
            "obbbbbbbo....obbbbbbbo",
            "oBBBBBBBo....oBBBBBBBo",
        ],
        0,
        12,
    ),
    12,
)

SMASH: Animation = [_SMASH_RAISED, _SMASH_DROP, _SMASH_CONTACT, _SMASH_BREAK, _SMASH_THROUGH]

# ---------------------------------------------------------------- hurt ----
# The flexed arm takes a hit, then droops with a bandage and sweat. 20 x 18.

_HURT_INCOMING: Frame = _paste(
    _FLEX_PEAK,
    [
        "y..",
        ".y.",
    ],
    1,
    6,
)

_STAR_BURST: Frame = [
    "..y..",
    ".yxy.",
    "yxxxy",
    ".yxy.",
    "..y..",
]

# Bicep deflates on impact (relaxed pose) and the burst lands where it was.
_HURT_IMPACT: Frame = _paste(_FLEX_RELAXED, _STAR_BURST, 4, 9)

_HURT_DROOP_A: Frame = [
    "....................",
    "....................",
    "....................",
    "....................",
    "..oooooooooo........",
    ".osssppppsssoo......",
    ".osssppppsssssso....",
    "..oosppppsssso.t....",
    "....ooppssssso.t....",
    ".......oodsso.......",
    "........odsso.......",
    "........odsso.......",
    "........odsso.......",
    ".......oWwwWo.......",
    ".......oWwwWo.......",
    ".......osssso.......",
    ".......odddso.......",
    "........oooo........",
]

_HURT_DROOP_B: Frame = [
    "....................",
    "....................",
    "....................",
    "....................",
    "..oooooooooo........",
    ".osssppppsssoo......",
    ".osssppppsssssso....",
    "..oosppppsssso......",
    "....ooppssssso......",
    ".......oodsso..t....",
    "........odsso..t....",
    "........odsso.......",
    "........odsso.......",
    ".......oWwwWo.......",
    ".......oWwwWo.......",
    ".......osssso.......",
    ".......odddso.......",
    "........oooo........",
]

HURT: Animation = [
    _HURT_INCOMING,
    _HURT_IMPACT,
    _HURT_IMPACT,
    _HURT_DROOP_A,
    _HURT_DROOP_B,
    _HURT_DROOP_A,
    _HURT_DROOP_B,
]

# -------------------------------------------------------------- gloves ----
# Red and blue gloves wind back and punch. 26 x 13.

_RED_GLOVE: Frame = [
    "..oooooo..",
    ".orrrrrro.",
    "orxxrrrrro",
    "orxrrrrrro",
    "orrrrRRrro",
    "orrrRRrrro",
    "orrRRrrrro",
    ".orrrrrro.",
    "..orrrro..",
    "..oRRRRo..",
    "..oooooo..",
]

_BLUE_GLOVE: Frame = _mirror(_RED_GLOVE, {"r": "u", "R": "U"})

_GLOVES_W, _GLOVES_H = 26, 13


def _gloves_frame(red_x: int, blue_x: int) -> Frame:
    canvas = _blank(_GLOVES_W, _GLOVES_H)
    canvas = _paste(canvas, _RED_GLOVE, red_x, 1)
    return _paste(canvas, _BLUE_GLOVE, blue_x, 1)


_GLOVES_APART: Frame = _gloves_frame(0, 16)

_GLOVES_CLOSE: Frame = _paste(
    _gloves_frame(2, 14),
    [
        "g.......................g",
        ".........................",
        "g.......................g",
        ".........................",
        "g.......................g",
    ],
    0,
    3,
)

_GLOVES_HIT: Frame = _paste(
    _paste(
        _gloves_frame(3, 13),
        [
            ".yy.",
            "yxxy",
            ".yy.",
        ],
        11,
        0,
    ),
    [
        ".yy.",
        "yxxy",
        ".yy.",
    ],
    11,
    9,
)

_GLOVES_RECOIL: Frame = _paste(
    _gloves_frame(1, 15),
    [
        ".y..",
        "...y",
        "y...",
        "..y.",
    ],
    11,
    3,
)

GLOVES: Animation = [_GLOVES_APART, _GLOVES_CLOSE, _GLOVES_HIT, _GLOVES_HIT, _GLOVES_RECOIL, _GLOVES_CLOSE]

ANIMATIONS: dict[str, Animation] = {
    "flex": FLEX,
    "smash": SMASH,
    "hurt": HURT,
    "gloves": GLOVES,
}
