/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/adhoc-executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Adhoc Execution
         * @description Run one framework directly as a one-stage ``adhoc`` cycle.
         *
         *     Same engine, persistence and event stream as a named cycle: progress and
         *     status live under ``/cycle-executions/{execution_id}``.
         */
        post: operations["create_adhoc_execution_api_v1_adhoc_executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Ai Config */
        put: operations["update_ai_config_api_v1_ai_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/config/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Config Status */
        get: operations["get_ai_config_status_api_v1_ai_config_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Delta Comparison */
        get: operations["get_delta_comparison_api_v1_analytics_delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/delta/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delta Case Changes
         * @description Per-test added/removed/regression/fix breakdown -- UI parity with ``testo diff``.
         *
         *     Computed on-demand from each run's own artifact snapshot every request (no
         *     caching): extracts both snapshots into a temp dir and matches cases by
         *     historyId/fullName/uuid, same as the CLI's full (non ``--metrics-only``) diff.
         */
        get: operations["get_delta_case_changes_api_v1_analytics_delta_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycle-executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cycle Execution */
        get: operations["get_cycle_execution_api_v1_cycle_executions__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycle-executions/{execution_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Cycle Execution Events */
        get: operations["stream_cycle_execution_events_api_v1_cycle_executions__execution_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cycles
         * @description List every cycle defined in the resolved configuration (UI parity with ``testo cycles list``).
         */
        get: operations["list_cycles_api_v1_cycles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles/{cycle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cycle
         * @description Resolved view of one cycle (UI parity with ``testo cycles show <name>``).
         */
        get: operations["get_cycle_api_v1_cycles__cycle__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles/{cycle}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Cycle Execution */
        post: operations["create_cycle_execution_api_v1_cycles__cycle__executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Overview */
        get: operations["get_dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/runs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Recent Runs */
        get: operations["get_dashboard_recent_runs_api_v1_dashboard_runs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/ai-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Ai Summary */
        get: operations["get_run_ai_summary_api_v1_runs__run_id__ai_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/ai-summary:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Run Ai Summary */
        post: operations["generate_run_ai_summary_api_v1_runs__run_id__ai_summary_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/pyramid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Pyramid
         * @description Unit/integration/e2e tier composition for a run (UI/API parity with ``testo report pyramid``).
         */
        get: operations["get_run_pyramid_api_v1_runs__run_id__pyramid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Reports */
        get: operations["get_run_reports_api_v1_runs__run_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdhocExecutionRequest
         * @description Run one framework directly, without a cycle in ``testosterone.yaml``.
         */
        AdhocExecutionRequest: {
            /** Args */
            args?: string[];
            /** Artifacts Root */
            artifacts_root?: string | null;
            /** Config Path */
            config_path?: string | null;
            /** Extra Env */
            extra_env?: {
                [key: string]: string;
            } | null;
            /**
             * Framework
             * @enum {string}
             */
            framework: "pytest" | "behave" | "behavex" | "command";
            /**
             * Persist
             * @default true
             */
            persist?: boolean;
            /**
             * Report Db
             * @default true
             */
            report_db?: boolean;
            /** Target Repo */
            target_repo: string;
            /** Timeout S */
            timeout_s?: number | null;
        };
        /** AiConfigStatusResponse */
        AiConfigStatusResponse: {
            /** Api Key Env Var */
            api_key_env_var: string | null;
            /**
             * Api Key Source
             * @enum {string}
             */
            api_key_source: "env" | "runtime_input";
            /** Configured */
            configured: boolean;
            /** Enabled */
            enabled: boolean;
            /** Key Present */
            key_present: boolean | null;
            /** Max Input Chars */
            max_input_chars: number;
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Model */
            model: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic";
            /** Retry Count */
            retry_count: number;
            /** Timeout S */
            timeout_s: number;
        };
        /** AiConfigUpdateRequest */
        AiConfigUpdateRequest: {
            /** Api Key Env Var */
            api_key_env_var?: string | null;
            /** Api Key Input */
            api_key_input?: string | null;
            /**
             * Api Key Source
             * @default env
             * @enum {string}
             */
            api_key_source?: "env" | "runtime_input";
            /**
             * Enabled
             * @default false
             */
            enabled?: boolean;
            /**
             * Max Input Chars
             * @default 16000
             */
            max_input_chars?: number;
            /**
             * Max Output Tokens
             * @default 300
             */
            max_output_tokens?: number;
            /**
             * Model
             * @default gpt-4o-mini
             */
            model?: string;
            /**
             * Provider
             * @default openai
             * @enum {string}
             */
            provider?: "openai" | "anthropic";
            /**
             * Retry Count
             * @default 1
             */
            retry_count?: number;
            /**
             * Timeout S
             * @default 8
             */
            timeout_s?: number;
        };
        /** AiSummaryResponse */
        AiSummaryResponse: {
            /** Confidence */
            confidence: ("low" | "medium" | "high") | null;
            /** Context Stats */
            context_stats: {
                [key: string]: number;
            };
            /** Error Code */
            error_code: string | null;
            /** Generated At */
            generated_at: number;
            /** Limitations */
            limitations: string[];
            /** Model */
            model: string | null;
            /** Provider */
            provider: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "v1";
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "no_summary_generated";
            /** Summary Text */
            summary_text: string | null;
        };
        /** CycleDetailResponse */
        CycleDetailResponse: {
            /** Description */
            description: string | null;
            /** Name */
            name: string;
            /** Stages */
            stages: components["schemas"]["StageSummary"][];
            trigger: components["schemas"]["CycleTriggerSummary"] | null;
        };
        /** CycleExecutionAcceptedResponse */
        CycleExecutionAcceptedResponse: {
            /** Events Url */
            events_url: string;
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running";
            /** Summary Url */
            summary_url: string;
        };
        /** CycleExecutionRequest */
        CycleExecutionRequest: {
            /** Artifacts Root */
            artifacts_root?: string | null;
            /**
             * Async Report Db
             * @default false
             */
            async_report_db?: boolean;
            /** Config Path */
            config_path?: string | null;
            /**
             * Fail Fast
             * @default false
             */
            fail_fast?: boolean;
            /**
             * Force
             * @default false
             */
            force?: boolean;
            /**
             * Persist
             * @default true
             */
            persist?: boolean;
            /**
             * Report Db
             * @default true
             */
            report_db?: boolean;
            /** Reporter Override */
            reporter_override?: string[] | null;
            /**
             * Stream
             * @default false
             */
            stream?: boolean;
            /** Workers Override */
            workers_override?: number | null;
        };
        /** CycleExecutionStatusResponse */
        CycleExecutionStatusResponse: {
            /** Artifacts Root */
            artifacts_root: string | null;
            /** Cycle */
            cycle: string;
            /** Error */
            error: string | null;
            /** Events Path */
            events_path: string | null;
            /** Execution Id */
            execution_id: string;
            /** Plan Result Path */
            plan_result_path: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
        };
        /** CycleListResponse */
        CycleListResponse: {
            /** Config Path */
            config_path: string | null;
            /** Items */
            items: components["schemas"]["CycleSummary"][];
        };
        /** CycleSummary */
        CycleSummary: {
            /** Description */
            description: string | null;
            /** Equipment */
            equipment: string[];
            /** Name */
            name: string;
            /** Stage Count */
            stage_count: number;
        };
        /** CycleTriggerSummary */
        CycleTriggerSummary: {
            /** Paths */
            paths: string[];
            /** Since Ref */
            since_ref: string | null;
        };
        /** DashboardDataFreshnessResponse */
        DashboardDataFreshnessResponse: {
            /** Degraded */
            degraded: boolean;
            /** Generated At */
            generated_at: number;
            /** Notes */
            notes: string[];
            /** Source Window Size */
            source_window_size: number;
        };
        /** DashboardHeadlineKpis */
        DashboardHeadlineKpis: {
            /** Baseline Run Id */
            baseline_run_id: string | null;
            /** Cycle */
            cycle: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Fail Count */
            fail_count: number | null;
            /** Health Pct */
            health_pct: number | null;
            /** Latest Run Id */
            latest_run_id: string | null;
            /** Latest Status */
            latest_status: string | null;
            /** Pass Count */
            pass_count: number | null;
        };
        /** DashboardOverviewResponse */
        DashboardOverviewResponse: {
            data_freshness: components["schemas"]["DashboardDataFreshnessResponse"];
            headline_kpis: components["schemas"]["DashboardHeadlineKpis"];
            performance_rollup: components["schemas"]["DashboardRollupResponse"];
            /** Recent Runs */
            recent_runs: components["schemas"]["DashboardRecentRunItem"][];
            reliability_rollup: components["schemas"]["DashboardRollupResponse"];
            report_links: components["schemas"]["DashboardReportLinksResponse"];
            /** Trend Indicators */
            trend_indicators: {
                [key: string]: components["schemas"]["DashboardTrendIndicator"];
            };
        };
        /** DashboardRecentRunItem */
        DashboardRecentRunItem: {
            /** Compare Url */
            compare_url: string | null;
            /** Created At */
            created_at: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Health Pct */
            health_pct: number | null;
            /** Returncode */
            returncode: number;
            /** Run Detail Url */
            run_detail_url: string;
            /** Run Id */
            run_id: string;
            /** Status */
            status: string | null;
        };
        /** DashboardRecentRunsResponse */
        DashboardRecentRunsResponse: {
            /** Generated At */
            generated_at: number;
            /** Items */
            items: components["schemas"]["DashboardRecentRunItem"][];
        };
        /** DashboardReportLinkResponse */
        DashboardReportLinkResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "available" | "missing" | "unknown";
            /** Url */
            url: string | null;
        };
        /** DashboardReportLinksResponse */
        DashboardReportLinksResponse: {
            allure: components["schemas"]["DashboardReportLinkResponse"];
            behave: components["schemas"]["DashboardReportLinkResponse"];
        };
        /** DashboardRollupResponse */
        DashboardRollupResponse: {
            status_summary: components["schemas"]["DashboardRollupSummaryResponse"];
            /** Top Highlights */
            top_highlights: string[];
        };
        /** DashboardRollupSummaryResponse */
        DashboardRollupSummaryResponse: {
            /** Improvements */
            improvements: number;
            /** Regressions */
            regressions: number;
            /** Unchanged */
            unchanged: number;
            /** Unknown */
            unknown: number;
        };
        /** DashboardTrendIndicator */
        DashboardTrendIndicator: {
            /** Delta Abs */
            delta_abs: number | null;
            /** Delta Pct */
            delta_pct: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "flat" | "unknown";
        };
        /** DeltaCaseChange */
        DeltaCaseChange: {
            /** Baseline Status */
            baseline_status: string | null;
            /** Current Status */
            current_status: string | null;
            /** Duration Delta Ms */
            duration_delta_ms: number | null;
            /** Group */
            group: string;
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "regression" | "fix" | "status_change";
            /** Name */
            name: string;
        };
        /** DeltaCaseChangesResponse */
        DeltaCaseChangesResponse: {
            /** Baseline Run Id */
            baseline_run_id: string;
            /** Changes */
            changes: components["schemas"]["DeltaCaseChange"][];
            /** Current Run Id */
            current_run_id: string;
        };
        /** DeltaComparisonMeta */
        DeltaComparisonMeta: {
            /** Baseline Run Id */
            baseline_run_id: string;
            /** Baseline Test Kind */
            baseline_test_kind: string;
            /** Current Run Id */
            current_run_id: string;
            /** Current Test Kind */
            current_test_kind: string;
        };
        /** DeltaComparisonResponse */
        DeltaComparisonResponse: {
            comparison: components["schemas"]["DeltaComparisonMeta"];
            /** Highlights */
            highlights: string[];
            metrics: components["schemas"]["DeltaMetricsResponse"];
            /** Stage Deltas */
            stage_deltas: components["schemas"]["DeltaStageDelta"][];
            status_summary: components["schemas"]["DeltaStatusSummaryResponse"];
        };
        /** DeltaMetricNode */
        DeltaMetricNode: {
            /** Absolute Delta */
            absolute_delta: number | null;
            /** Baseline Value */
            baseline_value: number | null;
            /**
             * Classification
             * @enum {string}
             */
            classification: "regression" | "improvement" | "neutral" | "unknown";
            /** Current Value */
            current_value: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher_is_better" | "lower_is_better";
            /** Reason */
            reason: string | null;
            /** Relative Delta Pct */
            relative_delta_pct: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "tests" | "pct" | "ms";
        };
        /** DeltaMetricsResponse */
        DeltaMetricsResponse: {
            performance: components["schemas"]["DeltaPerformanceMetrics"];
            reliability: components["schemas"]["DeltaReliabilityMetrics"];
        };
        /** DeltaPerformanceMetrics */
        DeltaPerformanceMetrics: {
            avg_case_ms: components["schemas"]["DeltaMetricNode"];
            metrics_duration_ms: components["schemas"]["DeltaMetricNode"];
            wall_duration_ms: components["schemas"]["DeltaMetricNode"];
        };
        /** DeltaReliabilityMetrics */
        DeltaReliabilityMetrics: {
            broken: components["schemas"]["DeltaMetricNode"];
            failed: components["schemas"]["DeltaMetricNode"];
            health_pct: components["schemas"]["DeltaMetricNode"];
            passed: components["schemas"]["DeltaMetricNode"];
            skipped: components["schemas"]["DeltaMetricNode"];
            total_tests: components["schemas"]["DeltaMetricNode"];
        };
        /** DeltaStageDelta */
        DeltaStageDelta: {
            /** Baseline Health Pct */
            baseline_health_pct: number | null;
            /** Baseline Passed */
            baseline_passed: number | null;
            /** Baseline Total Tests */
            baseline_total_tests: number | null;
            /**
             * Classification
             * @enum {string}
             */
            classification: "regression" | "improvement" | "neutral" | "unknown";
            /** Current Health Pct */
            current_health_pct: number | null;
            /** Current Passed */
            current_passed: number | null;
            /** Current Total Tests */
            current_total_tests: number | null;
            /** Framework */
            framework: string | null;
            /** Health Pct Delta */
            health_pct_delta: number | null;
            /** Stage Name */
            stage_name: string;
        };
        /** DeltaStatusSummaryResponse */
        DeltaStatusSummaryResponse: {
            /** Improvements */
            improvements: string[];
            /** Regressions */
            regressions: string[];
            /** Unchanged */
            unchanged: string[];
            /** Unknown */
            unknown: string[];
        };
        /** GenerateAiSummaryRequest */
        GenerateAiSummaryRequest: {
            /**
             * Force Refresh
             * @default false
             */
            force_refresh?: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthLiveResponse */
        HealthLiveResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HealthReadyResponse */
        HealthReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ReadinessCheck"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** ReadinessCheck */
        ReadinessCheck: {
            /** Detail */
            detail: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** RunDetail */
        RunDetail: {
            /** Audit Json */
            audit_json: string | null;
            /** Avg Case Ms */
            avg_case_ms: number | null;
            /** Broken */
            broken: number | null;
            /** Created At */
            created_at: number;
            /** Cycle */
            cycle: string | null;
            /** Failed */
            failed: number | null;
            /** Finished At */
            finished_at: number;
            /** Health Pct */
            health_pct: number | null;
            /** Metrics Duration Ms */
            metrics_duration_ms: number | null;
            /** Passed */
            passed: number | null;
            /** Returncode */
            returncode: number;
            /** Run Id */
            run_id: string;
            /** Skipped */
            skipped: number | null;
            /** Snapshot Dir */
            snapshot_dir: string | null;
            /** Stage Health */
            stage_health: components["schemas"]["StageHealth"][];
            /** Started At */
            started_at: number;
            /** Status */
            status: string | null;
            /** Target Repo */
            target_repo: string | null;
            /** Test Kind */
            test_kind: string;
            /** Total Tests */
            total_tests: number | null;
            /** Wall Duration Ms */
            wall_duration_ms: number;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            } | null;
            run: components["schemas"]["RunDetail"];
            /** Sync */
            sync: {
                [key: string]: unknown;
            } | null;
        };
        /** RunListItem */
        RunListItem: {
            /** Broken */
            broken: number | null;
            /** Created At */
            created_at: number;
            /** Cycle */
            cycle: string | null;
            /** Failed */
            failed: number | null;
            /** Health Pct */
            health_pct: number | null;
            /** Links Under Static */
            links_under_static: {
                [key: string]: string;
            };
            /** Passed */
            passed: number | null;
            /** Returncode */
            returncode: number;
            /** Run Id */
            run_id: string;
            /** Skipped */
            skipped: number | null;
            /** Status */
            status: string | null;
            /** Total Tests */
            total_tests: number | null;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunPyramidResponse */
        RunPyramidResponse: {
            /** E2E */
            e2e: number;
            /** Integration */
            integration: number;
            /** Message */
            message: string;
            /**
             * Shape
             * @enum {string}
             */
            shape: "healthy" | "top_heavy" | "mid_bulge" | "irregular";
            /** Unit */
            unit: number;
        };
        /** RunReportsResponse */
        RunReportsResponse: {
            /** Allure Server Url */
            allure_server_url: string | null;
            /** Artifact Links */
            artifact_links: string[];
            /** Static Links */
            static_links: {
                [key: string]: string;
            };
        };
        /** StageHealth */
        StageHealth: {
            /** Broken */
            broken: number | null;
            /** Failed */
            failed: number | null;
            /** Framework */
            framework: string | null;
            /** Health Pct */
            health_pct: number | null;
            /** Name */
            name: string;
            /** Passed */
            passed: number | null;
            /** Skipped */
            skipped: number | null;
            /** Total Tests */
            total_tests: number | null;
        };
        /** StageSummary */
        StageSummary: {
            /** Args */
            args: string[];
            /** Equipment */
            equipment: string;
            /** Name */
            name: string;
            /** Target Repo */
            target_repo: string;
            /** Timeout S */
            timeout_s: number | null;
            /** Workers */
            workers: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_adhoc_execution_api_v1_adhoc_executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdhocExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleExecutionAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ai_config_api_v1_ai_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConfigStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_config_status_api_v1_ai_config_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConfigStatusResponse"];
                };
            };
        };
    };
    get_delta_comparison_api_v1_analytics_delta_get: {
        parameters: {
            query: {
                current_run_id: string;
                baseline_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeltaComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delta_case_changes_api_v1_analytics_delta_cases_get: {
        parameters: {
            query: {
                current_run_id: string;
                baseline_run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeltaCaseChangesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cycle_execution_api_v1_cycle_executions__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleExecutionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_cycle_execution_events_api_v1_cycle_executions__execution_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cycles_api_v1_cycles_get: {
        parameters: {
            query?: {
                config_path?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cycle_api_v1_cycles__cycle__get: {
        parameters: {
            query?: {
                config_path?: string | null;
            };
            header?: never;
            path: {
                cycle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cycle_execution_api_v1_cycles__cycle__executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycle: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CycleExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleExecutionAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                recent_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_recent_runs_api_v1_dashboard_runs_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRecentRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponse"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_ai_summary_api_v1_runs__run_id__ai_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_run_ai_summary_api_v1_runs__run_id__ai_summary_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAiSummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_pyramid_api_v1_runs__run_id__pyramid_get: {
        parameters: {
            query?: {
                config_path?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPyramidResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_reports_api_v1_runs__run_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReportsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
